### PR TITLE
add Or

### PR DESCRIPTION
**Pull request by pitcons**

### CODE REVIEW

**Comment by admk** [comment]
Nice, thanks a lot for the pull request.

I think it would be interesting if you could override the ``__or__`` (``|``) operator in ``_Mimic`` to generate ``Or`` objects. What do you think?

**Comment by pitcons** [comment]
Thanks for the response.
I made small implementation of \__or\__ function. Is it what you mean?

I think we have some problems here.
For example, we can't write something like:

(Mimic('x') | Mimic('y')).match('y')

Because Mimic just returns raw value.
May be we must write some class Simple(_Mimic) for returning.
What do you think?

p.s.
Sorry for my terrible English.

**Comment by pitcons** [comment]
Hi again!
Can you provide some feedback about my commits?

**Comment by admk** [comment]
Sorry for the delay, I am merging this pull request now.

**Pull request merged**
